### ISSUE TITLE
Footer Text

### ISSUE THREAD

**Issue by jazinheira** [saylordotorg/edx-platform#13]
Need to update to saylor blurb.  Currently: EdX is a non-profit created by founding partners Harvard and MIT whose mission is to bring the best of higher education to students of all ages anywhere in the world, wherever there is Internet access. EdX's free online MOOCs are interactive and subjects include computer science, public health, and artificial intelligence.

**Comment by athuggins** [comment]
Might as well have it read our current Mission Statement:

"The mission of the Saylor Foundation is to make education freely available to all. Guided by the belief that technology has the potential to circumvent barriers that prevent many individuals from participating in traditional schooling models, the Foundation is committed to developing and advancing inventive and effective ways of harnessing technology in order to drive the cost of education down to zero."

**Comment by jazinheira** [comment]
The Saylor Academy, a 501(c)(3) non-profit based in Washington, D.C., empowers learners to set their own education goals, achieve mastery, and earn twenty-first century credentials within a rich network of peers, educators, and partners. Our students engage with expertly curated learning objects aligned to robust outcomes and assessments. The Academy is committed to advancing creative models of higher education champion access and encourage students to own their education.

**Comment by jazinheira** [comment]
The Saylor Academy, a 501(c)(3) non-profit based in Washington, D.C., empowers learners to set their own education goals, achieve mastery, and earn twenty-first century credentials within a rich network of peers, educators, and partners. Our students engage with expertly curated learning objects aligned to robust outcomes and assessments. The Academy is committed to advancing creative models of higher education that champion access and encourage students to own their education.

**Comment by athuggins** [comment]
Yeah, that works too. Go for it.

**Comment by jazinheira** [comment]
The Saylor Academy is a 501(c)(3) non-profit based in Washington, D.C., that empowers learners to set their own education goals, achieve mastery, and earn twenty-first century credentials within a rich network of peers, educators, and partners. Our students engage with expertly curated learning objects aligned to robust outcomes and assessments. The Academy is committed to advancing creative models of higher education that champion access and encourage students to own their education. Today, the Academy provides over 300 standard and college credit-aligned courses at the K-12, university, and career levels.

**Comment by jazinheira** [comment]
Ok, I created a brach - ja/footer-change - that reverted the "Text changes" commit.  I feel like something is up with the footer

**Comment by jazinheira** [comment]
Added new footer blurb, manually setting platform name.
