### ISSUE TITLE
Footer update

### ISSUE THREAD

**Issue by athuggins** [saylordotorg/edx-platform#21]
Footer reads "
© 2014 Saylor Academy, Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 3.0 Unported License.
", but should read
"
© 2014 Saylor Academy. Except where otherwise noted, content on this site is licensed under a <a href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported License</a>.
"
This is in lms/templates/footer.html.

**Comment by jazinheira** [comment]
Added link to CC license.
