### ISSUE TITLE
User accounts

### ISSUE THREAD

**Issue by athuggins** [saylordotorg/edx-platform#3]
We need individual user accounts for us (as admins) and to remove the default staff@example.com account.

**Comment by jazinheira** [comment]
Changed default @example.com accounts to @saylor.org and changed their passwords.

User info located in auth_users table in mysql db.

**Comment by jazinheira** [comment]
Added new accounts for Nate, Tanner, Walter, Reinholds, and John and made superusers.  Also set is_staff to true and added as course authors.
